server:
  servlet:
    context-path: /api

myblog:
  auth:
    token:
      sign-key: ${sign-key}
      valid-time: 3000000

spring:
  datasource:
    url: ${url}?allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${name}
    password: ${pass}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
